version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
    volumes:
      - .:/myapp
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: postgres
      PASSWORD: password
    ports:
      - "3000:3000"
    init: true
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgresql-data: